### ISSUE TITLE
校对任务认领

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/Cookbook-for-R-Chinese#18]
## 任务说明

对照中文版<https://openbiox.github.io/Cookbook-for-R-Chinese/>和英文版<http://www.cookbook-r.com/>校对翻译内容，实际的内容都放在[book目录](https://github.com/openbiox/Cookbook-for-R-Chinese/tree/master/book)下，请先fork仓库，校对后以合并请求的形式提交。

## 要求

- 请大家在正式校对前务必阅读[校对基本要求](https://github.com/openbiox/openbiox-Translation/wiki/%E6%A0%A1%E5%AF%B9%E5%9F%BA%E6%9C%AC%E8%A6%81%E6%B1%82(beta))。
- 中文内容与英文意思不对应或者中文理解不顺畅，请进行修改。有任何问题请在群里讨论。
- 对未完成翻译的英文进行翻译。
- 确认内容目录层级正确。章是1级标题，以一个`#`开头，2级标题通常只有2个，一个是“问题”，一个是“方案”。总体不能超过5级标题。如果存在任何问题，比如我看到有的“方案”写成了解决，都请修正。
- 删除原文链接。

**如果是新增的内容**（原文没有，但译文有的）请不要删除，如果有问题可以修改！

请大家不要自己更新bookdown的相关内容！当然你可以在本地自己看看，我们最后只接收Rmd文件内部的更改。

## 认领

校对任务按章认领，不同的章工作量不太一样，请大家先看下工作量以及自己的空余时间选择。原则上，半个月内完成提交。

- [x] 01
- [x] 02
- [x] 03
- [x] 04
- [x] 05
- [x] 06
- [x] 07
- [x] 08
- [x] 09
- [x] 10

**Comment by fei0810** [comment]
校对任务领取：2、3、6 章

**Comment by ShixiangWang** [comment]
@fei0810 ok. 问一下，排版规范的直角方括号是怎么打出来的？

**Comment by RuiYang1994** [comment]
认领1

**Comment by RuiYang1994** [comment]
认领1,4

**Comment by fei0810** [comment]
> @fei0810 ok. 问一下，排版规范的直角方括号是怎么打出来的？
这是个好问题 :)，不知道你用的 Mac还是Windows，如果是Mac的话据说很好打出来直角引号，但是Windows上就需要对输入法进行一些设置。大多数输入法是支持自定义符号的，我用的是QQ输入法，在属性设置-高级-自定义标点设置里，我把中文状态下键盘上的[ 和 ] 改成了 「和」。其它输入法应该也有类似的方法

**Comment by w1nsan** [comment]
认领 5，10

**Comment by ShixiangWang** [comment]
@w1nsan @RuiYang1994 好的～

**Comment by 2015qyliang** [comment]
顺序认领 7，8，9
