### ISSUE TITLE
翻译任务认领

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/Cookbook-for-R-Chinese#2]
请在翻译之前仔细阅读[README](https://github.com/openbiox/Cookbook-for-R-Chinese)的“如何翻译和修改”部分。

先在下方浏览没有打钩的文档，在下方留言认领，然后fork本仓库进行翻译，翻译完成后向本仓库提交合并请求。认领后半个月内需要完成任务的提交。

翻译内容格式请参考已翻译的文档。

蓝色字体为链接，请点击查找相关的文档。

原文位于<http://www.cookbook-r.com/>，很容易找到。

---

## 翻译认领

[图形](https://github.com/openbiox/Cookbook-for-R-Chinese/tree/master/cookbook/Graphs)

- [x] ggplot标题
- [x] ggplot多图
- [x] ggplot分面
- [x] ggplot绘制分布
- [x] ggplot图例
- [x] ggplot线条
- [x] ggplot颜色
- [x] 其他有趣图形-相关矩阵
- [x] 图形混杂-抗混淆位图输出
- [x] 图形混杂-输出到文件-PDF-PNG-TIFF-SVG
- [x] 图形混杂-形状和线形
- [x] 图形混杂-字体

[操纵数据](https://github.com/openbiox/Cookbook-for-R-Chinese/tree/master/cookbook/Manipulating_data)

- [x] 序列数据-寻找唯一值序列
- [x] 序列数据-用最后的非NA值填充NA值

[脚本与函数](https://github.com/openbiox/Cookbook-for-R-Chinese/tree/master/cookbook/Scripts_and_functions)

- [x] 测量运行时间
- [x] 调试脚本或函数
- [x] 获取一个包的函数和对象列表

*** 
需要原创的（自己设置数据集和方案，比较有挑战，欢迎认领）：

- [x] [使用grep,sub,gsub进行搜索和替换](https://github.com/openbiox/Cookbook-for-R-Chinese/blob/master/cookbook/Strings/%E4%BD%BF%E7%94%A8grep%2Csub%2Cgsub%E8%BF%9B%E8%A1%8C%E6%90%9C%E7%B4%A2%E5%92%8C%E6%9B%BF%E6%8D%A2.md)
- [x] 创建和运行一个脚本 (脚本与函数部分)

**Comment by huimeiwang** [comment]
领ggplot图例线条颜色

**Comment by ShixiangWang** [comment]
@huimeiwang ok

**Comment by w1nsan** [comment]
领：ggplot 标题/多图/分面/绘制分布

**Comment by RuiYang1994** [comment]
领： 测量运行时间；调试脚本或函数；获取一个包的函数和对象列表

**Comment by Byronxy** [comment]
领： 序列数据-寻找唯一值序列; 序列数据-用最后的非NA值填充NA值

**Comment by ShixiangWang** [comment]
@w1nsan @RuiYang1994 @Byronxy Ok.

**Comment by ShixiangWang** [comment]
领  使用grep,sub,gsub进行搜索和替换

**Comment by w1nsan** [comment]
领:图形混杂-字体/图形混杂-输出到文件

**Comment by ShixiangWang** [comment]
@w1nsan 这3个？
![image](https://user-images.githubusercontent.com/25057508/55289403-efb32280-53f8-11e9-93a7-0abdd044e60f.png)

**Comment by 2015qyliang** [comment]
认领 “其他有趣图形-相关矩阵”

**Comment by ShixiangWang** [comment]
@2015qyliang okay

**Comment by 2015qyliang** [comment]
拟认领 “ 创建和运行一个脚本 (脚本与函数部分)”  ， 周末刚优化了计算细菌基因组间核心蛋白比例的分析脚本（使用diamond进行蛋白比对，https://github.com/2015qyliang/POCP），如果觉得数据与内容合适，我就在整理一下 然后 pull request。。。

**Comment by ShixiangWang** [comment]
@2015qyliang 好，take a try。样例数据尽量简化，可以直接写入文本。加油～

**Comment by 2015qyliang** [comment]
认领“图形混杂-抗混淆位图输出”

**Comment by ShixiangWang** [comment]
@2015qyliang okay

**Comment by ShixiangWang** [comment]
翻译任务应该完成了。 如果还有在进行的at我一下。
