### ISSUE TITLE
Cookbook4r翻译小队最后一次团体任务

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/Cookbook-for-R-Chinese#25]
## 目标

将markdown代码块修改为rmarkdown代码块。注意，如果存在不能运行的示例代码块，保留不更改。

操作对象，10个rmarkdown文本

![image](https://user-images.githubusercontent.com/25057508/57278006-f6a81180-70d7-11e9-90f2-2c8734b45488.png)

如

![image](https://user-images.githubusercontent.com/25057508/57278464-17bd3200-70d9-11e9-8ba4-4de4920175b2.png)

就不要更改了。

而

![image](https://user-images.githubusercontent.com/25057508/57278488-260b4e00-70d9-11e9-8d26-b454f249ed5a.png)

可以修改为

![image](https://user-images.githubusercontent.com/25057508/57278539-4a672a80-70d9-11e9-83dc-0beb92cee975.png)

修改后请在本地测试是否能正常运行，只提交修改的rmarkdown内容，预览的html或pdf请不要提交。

## 认领

请大家先看下工作量以及自己的空余时间选择。原则上，半个月内完成提交。

- [x] 01
- [x] 02
- [x] 03
- [x] 04
- [x] 05
- [x] 06
- [x] 07
- [x] 08
- [x] 09
- [x] 10

最后，参与了贡献却没有在仓库主页或https://openbiox.github.io/Cookbook-for-R-Chinese/ 显示的成员请@我。

**Comment by RuiYang1994** [comment]
认领1，4

**Comment by ShixiangWang** [comment]
@RuiYang1994 Okay :)

**Comment by 2015qyliang** [comment]
认领 07 + 08

**Comment by w1nsan** [comment]
认领 05 +10

**Comment by hyacz** [comment]
认领 2,3,6,9

**Comment by ShixiangWang** [comment]
@hyacz 你大概多久可以提交合并？

**Comment by hyacz** [comment]
> @hyacz 你大概多久可以提交合并？

我已经提交 commit 了，https://github.com/openbiox/Cookbook-for-R-Chinese/commit/856154ea9797884a55bd8b9c340eca3fb806fb5c

**Comment by ShixiangWang** [comment]
@hyacz 时间有点久，没看到~Thanks
