### ISSUE TITLE
翻译文档整合任务

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/Cookbook-for-R-Chinese#4]
将<https://github.com/openbiox/Cookbook-for-R-Chinese/tree/master/cookbook>中每个目录下的一章的文件内容整合到<https://github.com/openbiox/Cookbook-for-R-Chinese/tree/master/book>对应的文件中。

该任务的目的是方便接下来的校对工作，领取任务的半个月内应当完成任务的提交。

需要做的事情：

- 对照着<http://www.cookbook-r.com/>展示的顺序，将cookbook目录每个文件的内容依次拷贝到<book>下一章的文件中
- 所有标题降级处理，对标题增加一个`#`，也就是原文件中的`#`变成`##`，`##`变成`###`。
- 删掉含`<!-- more -->`的内容。
- 删除原文链接以及原文链前的`---`等分隔符

注意，在原网站中，每个章下面又把内容分为了几块，特别是图形

<http://www.cookbook-r.com/Graphs/>

我们把它们当做连续的章节从上到下整理即可。（后期可能需要对顺序进行调整）不这样分块的原因是目录层级太多章节就显得太复杂了。

下方留言认领，可以参考[第一章](https://github.com/openbiox/Cookbook-for-R-Chinese/blob/master/book/01-basics.md)

08、09还有很多翻译工作未完成，暂时不纳入整合任务

## 认领

- [x] 01
- [x] 02
- [x] 03
- [x] 04
- [x] 05
- [x] 06
- [x] 07
- [x] 10

**Comment by 2015qyliang** [comment]
顺序认领 02

**Comment by hyacz** [comment]
认领 03-05（已推回主分支https://github.com/openbiox/Cookbook-for-R-Chinese/commit/6134e48604aaed875dde4c449949a5b6fa5aa7bd ）

**Comment by w1nsan** [comment]
认领 06

**Comment by RuiYang1994** [comment]
认领7

**Comment by fei0810** [comment]
@ShixiangWang 现在翻译和合并任务都认领完了么？我们是否可以开始认领校对任务
